server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: user-service # 注册到 Nacos 上的服务名（Gateway 转发就靠这个名字）
  cloud:
    nacos:
      # discovery和config共享这个nacos地址
      server-addr: vdebian.local:8848
      #服务发现配置
      discovery:
        namespace: d8f34ca5-d036-46a4-babe-d0b1cdcbc133 # 命名空间 ID（可选，如果不配置则在 public）
        group: TEST_GROUP # 分组名（可选，默认 DEFAULT_GROUP）
        #cluster-name: HANGZHOU # 集群名（可选，用于跨机房容灾）

      #配置中心配置
      config:
        namespace: d8f34ca5-d036-46a4-babe-d0b1cdcbc133
        group: TEST_GROUP
        file-extension: yaml
  # 执行到 import 行时，去 Nacos 下载配置,会覆盖本地同名配置
  config:
    import:
      - nacos:${spring.application.name}.yaml?group=TEST_GROUP # 导入 Nacos 配置


